### PR TITLE
Fix Swipe on iOS 13

### PR DESCRIPTION
**Pull request by faran312**
On iOS 13, hammer can accept event **pancancel** from the device. This event will triggered when user swipe and scrolling at the same time. And then it will stop the carousel in the halfway. So, I just add an event to handle this.

### CODE REVIEW

**Comment by akhilsp32** [comment]
Can anyone please merge this fix?

**Comment by sheikalthaf** [comment]
@faran312 thanks for the PR. I got busy with my job. Can you please resolve the conflict due to recent PR merge.

Thanks

**Comment by faran312** [comment]
Sure!

**Comment by faran312** [comment]
Conflict resolved! @sheikalthaf

**Comment by sheikalthaf** [comment]
LGTM

**Pull request merged**
