### PR TITLE
Fix issue with ObjectUnsubscribedError

### PR DESCRIPTION
**Pull request by mczachurski**
This is another fix for issue with ObjectUnsubscribedError. This error occurs very often when component is destroyed (and after that timer executes function whcih requires component).

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@mczachurski This happens to me too, I thought it was another library or angualr related error, but noticed the `ObjectUnsubscribedErrorImpl` error only after triggering the reset function on the carousel component.

**Comment by daco** [comment]
Can @sheikalthaf merge this pull request? I got this error to. Thank you!

**Comment by sheikalthaf** [comment]
@mczachurski thanks for the PR. I was busy with my work. can you resolve the conflict. so that i can merge the PR.

Thanks

**Comment by mczachurski** [comment]
Hi, I resolved conflicts.

**Comment by santoshyadav198613** [comment]
Thanks @mczachurski ,
It will be available in next release.

**Pull request merged**
