### PR TITLE
Added support for Angular 9

### PR DESCRIPTION
**Pull request by euangoddard**

### CODE REVIEW

**Comment by doliG** [comment]
@sheikalthaf Hello dear maintainer

**Comment by ChrisProlls** [comment]
+1 !
We need this for our critical migration about one of our business application !

**Comment by Krgauravfreelancer** [comment]
Hi maintainer, we need this, please take a look and merge PR if suitable

**Comment by sheikalthaf** [comment]
Hi all,

Sorry for the late reply. I was busy with my job. I will look at the PR and merge asap

Thanks

**Comment by sheikalthaf** [comment]
LGTM

**Comment by euangoddard** [comment]
@sheikalthaf could you please let me know when you have bumped the package version on NPM so that I can revert to using the official package and can deprecate my fork?

**Comment by sheikalthaf** [comment]
@euangoddard building the library is failing. Can you help me to build the library so that I publish to npm

**Comment by euangoddard** [comment]
@sheikalthaf how are you invoking the build? I think you need to specify the project off the top-of-my head. It might be worth comparing the fork I made. There might have been some changes to get it to deploy to NPM. If I get a chance I'll take a look today

**Comment by euangoddard** [comment]
@sheikalthaf I've found the differences I added to get this working. Check this out: https://github.com/sheikalthaf/ngu-carousel/compare/master...Stockopedia:fork. You'll need to pick the bits that you need as I had to rename the package, etc.

**Comment by sheikalthaf** [comment]
@euangoddard I'm just running this command `ng build --prod --project ngu-carousel`. And getting error like this.
image

Can you try this command in your local.

**Comment by sheikalthaf** [comment]
@euangoddard latest changes published to npm. Can you please check that.

Thanks

**Pull request merged**
