### PR TITLE
Use isPlatformBrowser rather then checking for the existance of window

### PR DESCRIPTION
**Pull request by fridolin-koch**
Fixes https://github.com/sheikalthaf/ngu-carousel/issues/14

### CODE REVIEW

**Comment by fridolin-koch** [comment]
The only other usages are in:

`_carouselInterval()` which is called inside the changed if-block.

The other usage is in `_onWindowScrolling()` which is also called inside the changed if-block. (It is also called inside `_carouselInterval()` but this call is transitively guarded by the if)

So I guess it is sufficient.

If I missed something just let me know, I'll fix it then

Best regards,
Frido

**Comment by sheikalthaf** [comment]
@fridolin-koch I think you missed this Fn `_storeCarouselData()`

**Comment by fridolin-koch** [comment]
@sheikalthaf It already contains a check https://github.com/sheikalthaf/ngu-carousel/blob/master/projects/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts#L452

**Comment by sheikalthaf** [comment]
@fridolin-koch Thanks for the clarification. code format leads me wrong.

**Pull request merged**
